// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lansvkgrfhwqhakpzshe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhbnN2a2dyZmh3cWhha3B6c2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDM1OTQsImV4cCI6MjA2MzExOTU5NH0.nk_wRVh8FK85h00-KN5k_PbDZvgqjsJx383Yj6VWC6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);